---
title: "Virustotal_aRules"
author: "Ángel Sergio"
date: '2022-05-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r librerias}
library(dplyr)
library(arules)
library(magrittr)
library(rmarkdown)
library(readr)
library(stringr)
library(tidyverse)
```


```{r lectura, include=FALSE}
virus <- read_csv('../VirusTotal/data/virusTotal.csv')

 
lista <- list(additional_info.androguard.RiskIndicator.PERM.DANGEROUS = 0,
              additional_info.androguard.RiskIndicator.PERM.GPS = 0,
              additional_info.androguard.RiskIndicator.PERM.NORMAL = 0,
              additional_info.androguard.RiskIndicator.PERM.PRIVACY = 0,
              additional_info.androguard.RiskIndicator.PERM.INTERNET = 0,
              additional_info.androguard.RiskIndicator.PERM.INSTANT = 0,
              additional_info.androguard.RiskIndicator.PERM.SMS = 0,
              additional_info.androguard.RiskIndicator.PERM.MONEY = 0,
              additional_info.androguard.RiskIndicator.PERM.SYSTEM = 0,
              additional_info.androguard.RiskIndicator.PERM.CALL = 0,
              additional_info.androguard.RiskIndicator.PERM.SIGNATURE = 0,
              additional_info.androguard.RiskIndicator.PERM.DEVELOPMENT = 0,
              additional_info.androguard.RiskIndicator.PERM.PRE23 = 0,
              additional_info.androguard.RiskIndicator.PERM.APPOP = 0,
              additional_info.androguard.RiskIndicator.PERM.EPHEMERAL = 0,
              additional_info.androguard.RiskIndicator.PERM.PREINSTALLED = 0,
              additional_info.androguard.RiskIndicator.PERM.INSTALLER = 0,
              additional_info.androguard.RiskIndicator.PERM.RUNTIME = 1)

virus <- replace_na(virus, lista)

```



```{r lectura, include=FALSE}
rules <- virus %>%
   select(c(additional_info.androguard.RiskIndicator.PERM.DANGEROUS,
             additional_info.androguard.RiskIndicator.PERM.GPS,
             additional_info.androguard.RiskIndicator.PERM.NORMAL,
             additional_info.androguard.RiskIndicator.PERM.PRIVACY,
             additional_info.androguard.RiskIndicator.PERM.INTERNET,
             additional_info.androguard.RiskIndicator.PERM.INSTANT,
             additional_info.androguard.RiskIndicator.PERM.SMS,
             additional_info.androguard.RiskIndicator.PERM.MONEY,
             additional_info.androguard.RiskIndicator.PERM.SYSTEM,
             additional_info.androguard.RiskIndicator.PERM.CALL,
             additional_info.androguard.RiskIndicator.PERM.SIGNATURE,
             additional_info.androguard.RiskIndicator.PERM.DEVELOPMENT,
             additional_info.androguard.RiskIndicator.PERM.PRE23,
             additional_info.androguard.RiskIndicator.PERM.APPOP,
             additional_info.androguard.RiskIndicator.PERM.EPHEMERAL,
             additional_info.androguard.RiskIndicator.PERM.PREINSTALLED,
             additional_info.androguard.RiskIndicator.PERM.INSTALLER,
             additional_info.androguard.RiskIndicator.PERM.RUNTIME
             ))
View(rules)

cut_by_quantiles <- 
  function(col){
    labels <- c("very low", "low", "medium", "high", "very high")
    col %>% 
      sapply(., cut(breaks = quantile(.), labels = labels))
  }

df_cut_by_quantiles <- 
  function(df){
    df_without_numeric <- df[!is.numeric(df)]
    df_numeric <- 
      select_if(is.numeric)
    df_numeric <- 
      df_numeric %>% 
      lapply(cut_by_quantiles)
    cbind(df_without_numeric, df_numeric)
  }

df_test <- 
  rules  %>% 
  df_cut_by_quantiles()


```



```{r}
r1 <- apriori(df_2, parameter = list(supp=0.01, conf=0.5))
inspect(r1)
```